# Site settings
title: "khast3x_club"
email: khast3x@riseup.net
description: "Information security, tips, hacks and giggles"
baseurl: ""
url: "khast3x.github.io"
title_image: "https://i.imgur.com/5zVB9Ja.png"
title_description: "Information Security.<br>Notes and thoughts on my side-projects.<br>Consider any information shared on this blog as educational material, you are responsible for your actions."
google_analytics: "UA-113498686-1"
# disqus_account: cartenoire
github_repository: https://github.com/khast3x
addthis_id: ra-5a7c54b6a73cab6d
post_limit: 5

# Social usernames/URLs
twitter_username: kh4st3x
github_username:  khast3x
# instagram_username:
# reddit_username:
# linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
# google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
# stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
# xing_link:
# facebook_link:

# Jekyll SEO plugins
url: https://khast3x.club
author: khast3x

social:
    name: khast3x
    links:
        - https://twitter.com/kh4st3x
        - https://github.com/khast3x

# Footer
footer_right: "<i class=\"fa fa-github-alt\"></i><a href=\"https://github.com/jacobtomlinson/carte-noire\"> theme</a>"
footer_left: "<i class=\"fa fa-twitter\"></i> <a href=\"https://twitter.com/kh4st3x\">twitter</a><br><i class=\"fa fa-github\"></i> <a href=\"https://github.com/khast3x\">github</a>"
# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag

  defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      image: "https://i.imgur.com/5zVB9Ja.png"
