# Site settings
title: "khast3x infosec notes"
email: khast3x@riseup.net
description: "Information security"
baseurl: ""
url: "khast3x.github.io"
title_image: "https://i.imgur.com/5zVB9Ja.png"
title_description: "Consider any information shared on this blog as educational material, you are responsible for your actions. Drop me a message for collab or CFP suggestions"
google_analytics: "UA-113498686-1"
# disqus_account: cartenoire
github_repository: https://github.com/khast3x
# addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: kh4st3x
github_username:  khast3x
# instagram_username:
# reddit_username:
# linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
# google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
# stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
# xing_link:
# facebook_link:

# Footer
footer_right: "<a href=\"https://github.com/jacobtomlinson/carte-noire\">carte noire theme</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
plugins:
  - jekyll-sitemap
